### ISSUE TITLE
seemingly can't uninstall

### ISSUE THREAD

**Issue by RealTheRev** [ethangreen-dev/lovely-injector#100]
console keeps opening when starting balatro, even if i have removed all mod files i could find.
not even verifying game files on steam worked, and now the console opens every time on startup
is there a way to get rid of it?

**Comment by ethangreen-dev** [comment]
Hey @RealTheRev, have you double checked that `version.dll` is deleted from the game directory? That's the folder that contains Balatro.exe among other game files.

**Comment by RealTheRev** [comment]
I've tried deleting that file, but that just stops the game from starting,
and when i verify the files it comes back with the console opening again on
startup.

**Comment by ethangreen-dev** [comment]
That doesn't make much sense to me - validating the game shouldn't cause `version.dll` to come back. Could you share a screenshot of your game directory and of the console window that appears?
