### ISSUE TITLE
version.dll deletes itself upon leaving the zipped folder

### ISSUE THREAD

**Issue by letthemeatrakes** [ethangreen-dev/lovely-injector#101]
Hi! I don't know much about this kind of stuff, and I'm confused.

I've followed the listed steps (including putting folders in exceptions for my anti-virus), but the version.dll goes to 0 bytes instantly whenever not zipped up; whether that be copying it to somewhere else or unzipping the folder it comes in. I've seen someone else had this issue, but they closed it themselves without providing an explanation.

Additionally, when I attempt to download the injector from here, I always receive this popup:

"C:\Users\(my name)\Downloads\dVuB1XNh.zip.part could not be saved, because the source file could not be read.

Try again later, or contact the server administrator."

Wondering if anyone could help me out!

**Comment by Aurelius7309** [comment]
That's probably your anti-virus interfering, try this: https://github.com/Steamopollys/Steamodded/wiki#step-1-anti-virus-setup

**Comment by ethangreen-dev** [comment]
Agreed, change your AV settings as per the Steamodded wiki.
