### ISSUE TITLE
MacOS version searches for mods in wrong directory

### ISSUE THREAD

**Issue by LesserQuire** [ethangreen-dev/lovely-injector#26]
running run_lovely.sh shows this line
`INFO - Using mod directory at "/Users/noelle/Library/Application Support/Balatro\\Mods` which is this folder
<img width="256" alt="image" src="https://github.com/ethangreen-dev/lovely-injector/assets/117785103/67a961bb-4861-42dc-b0e7-891a986e36a8">
changing it to Balatro/Mods should fix it. I was able to check that putting mods in the shown folder works.

**Comment by ethangreen-dev** [comment]
This should have been resolved in #18 but I'll keep this issue open until we have concrete evidence that it's fixed.
