### ISSUE TITLE
Unexpected U+FEFF when patching game.lua

### ISSUE THREAD

**Issue by ChromaPIE** [ethangreen-dev/lovely-injector#38]
TOML patches for other files works fine (at least for globals.lua, tag.lua and functions/state_events.lua which are present in my toml), but when patching game.lua, an unexpected unicode character is breaking the syntax. Decompiled game.lua using Balamod shows that it's in UTF-8 with BOM, while a couple of others I checked are all in UTF-8, don't know if it's actually caused by this. Here's what the dumped file looks like in VSCode:

![5cf03ddcc7070d4f4f97b0a533e55f4b](https://github.com/ethangreen-dev/lovely-injector/assets/56111366/0dd61006-af67-4fc1-a527-12c967a9efa4)

EDIT: just tried putting re-encoded game.lua under %appdata%/balatro and got things going. guess it's the exact cause.

**Comment by Aurelius7309** [comment]
Do you have a Steamodded installation via the classic injector on your game? It doesn't get along with lovely very well, and I think I've seen this exact issue caused by both being present.

**Comment by ethangreen-dev** [comment]
Seems like this is resolved?

**Comment by ChromaPIE** [comment]
> Do you have a Steamodded installation via the classic injector on your game? It doesn't get along with lovely very well, and I think I've seen this exact issue caused by both being present.

yeah. i play the game and mess around w/ stuff on mobile more often and due to https://github.com/ethangreen-dev/lovely-injector/issues/32 the toml patch isn't working as intended so i have to use the injector. maybe i should get the vanilla game without steamodded injection and see if the UTF-8 with BOM is actually caused by Steamodded but not the original game.
