### ISSUE TITLE
no mods (besides steammodded) working

### ISSUE THREAD

**Issue by coolboy7D** [ethangreen-dev/lovely-injector#44]
So, I'm not sure what I'm doing wrong here.
No matter what mods I use, when I open Balatro it is completely _**unmoddded**_.
I follow all of the instructions; I copy the version.dll to the game's directory,
I put my mods at %appdata%\Balatro\Mods and still nothing happens.
Do I place a new folder for each mod and extract the .zips to there?
I'm not really sure.

**Comment by coolboy7D** [comment]
I would also like to mention that the lovely window does open, so lovely itself is working; however it doesnt take any mods into account.

**Comment by coolboy7D** [comment]
I seem to be able to have mods now, but only after extracting the contents of every zip into individual folders for each mod, i think it would be nice to clarify this in like the install instructions (+ anything besides steammodded mods work...)

**Comment by ethangreen-dev** [comment]
Hi, this is unfortunately not a support forum. I recommend you ask in in Steamodded-specific support channels for help with your issues, whether they've been resolved or not. This repository specifically does not going into details on how specific mods / patches should be installed other than the small blurb at the end of the install guide:

> **Important:** Mods with Lovely patch files (lovely.toml or in lovely/*.toml) must be installed into their own folder within the mod directory. No exceptions!

Thanks
