### ISSUE TITLE
Newline handling

### ISSUE THREAD

**Issue by english5040** [ethangreen-dev/lovely-injector#52]
Currently a lot of lovely patches have broken indentation due to how newlines are handled: in pattern patches, after .split() on a payload containing a trailing newline, the empty string after that newline is returned, and indent is prepended to that empty string. In addition, regex patches sometimes have strange behavior with newlines.

We should be consistent and use [split_inclusive](https://doc.rust-lang.org/std/primitive.str.html#method.split_inclusive) and Rope::raw_lines() everywhere.

**Comment by ethangreen-dev** [comment]
Should be an easy enough fix for the pattern patch, but Regex will be a bit more tricky without something to test against.
