### ISSUE TITLE
Breaks syntax if the lua file do not have a final new line

### ISSUE THREAD

**Issue by dadahsueh** [ethangreen-dev/lovely-injector#53]
Maybe its my problem, but I am modding the game [Moonring](https://store.steampowered.com/app/2373630/Moonring/). And I would encounter `Error: Syntax error: state_game.lua:21716: '=' expected near '<eof>'`.
- So I looked at the dumped lua files and compared with the original files.
- The original `state_game.lua` does not have a final empty line (so it ended with `end`), and the dumped file would remove the last character and end with `en`.
- And I had a look at all other working files, they had empty new lines, and the dumped files would remove these new lines.
- FYI this is on Windows, and I tried pattern, regex, copy all with the same results as long as I touch the file it would break, I suspect the `lib.rs` file? But I do not understand rust... Maybe `let buf = slice::from_raw_parts(buf_ptr, (size - 1) as _);`?

**Comment by ethangreen-dev** [comment]
Heard, send me a copy of your mod so I can reproduce the problem.

**Comment by dadahsueh** [comment]
> Heard, send me a copy of your mod so I can reproduce the problem.

I made this .toml file in a folder in the Mods directory and was able to reproduce the issue.
```
[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.regex]
target = "state_game.lua"
pattern = "anything not in the script"
position = "at"
payload = "something"
```

**Comment by dadahsueh** [comment]
#54 I have no idea what I'm doing. But this solved the issue of removing whatever the last char is.
