### ISSUE TITLE
Game crashes when any of the buttons in the settings screen is clicked

### ISSUE THREAD

**Issue by grkmndr** [ethangreen-dev/lovely-injector#60]
I've just tried configuring this stuff to be able to play with mods so bear with me if I've missed some key steps. (I'm running this on a MacBook M1 Pro)

This is how it looks in ~/Library/Application Support/Balatro folder:
<img width="431" alt="Screenshot 2024-07-07 at 18 25 59" src="https://github.com/ethangreen-dev/lovely-injector/assets/9133843/d9d5cddb-0746-42c9-9ec4-5abc4d470d1f">

When I run the game I'm able to play with MoreSpeeds and quickrestart mods without a problem. (Although I haven't been able to run the Brainstorm mod successfully but that's an issue for another day.)

But whenever I go into the Options->Settings screen in-game and click on any of the buttons (Game, Video, Graphics, Back etc.) the game crashes. Here's the log:

[lovely-2024.07.07-18.20.14.log](https://github.com/user-attachments/files/16119841/lovely-2024.07.07-18.20.14.log)

**Comment by Aurelius7309** [comment]
This is an issue with MoreSpeeds, the custom speed box introduced this problem. It should no longer crash if you remove that part from the mod or roll it back to a previous version that didn't have the custom speed box: 
[MoreSpeeds.zip](https://github.com/user-attachments/files/16132875/MoreSpeeds.zip)

**Comment by grkmndr** [comment]
Thanks a lot this solves the issue.
