### ISSUE TITLE
It is necessary to specify a version of Proton

### ISSUE THREAD

**Issue by diegofer-dev** [ethangreen-dev/lovely-injector#64]
Hi everyone. Loving this project so far!

I don't know if this is really a bug but I'm reporting it just in case.
Right now I'm using Linux on my main machine (not the Steam Deck) where I'm running Balatro, the game I'm trying to mod.
I was following the instructions specified in the README of the main branch but was unable to launch the game again on Steam.
That was until I set the flag of "Force the use of a specific Steam Play compatibility tool" to true, and set the Proton version to 9.0-2 (I believe the version doesn't really matter). After this the injector launched, and the game was detecting the mods.

Again I apologize if this isn't really a bug but I felt maybe the developers wanted to know this so they can add a small note on the documentation.

Cheers!

**Comment by BNTFryingPan** [comment]
works perfectly fine for me (balatro on linux) without doing that. not on steam deck, but shouldnt make a difference

**Comment by nycki93** [comment]
This worked for me; the default version was Proton 7.0. After switching to Proton 9.0 it's working.
