### ISSUE TITLE
README needs AV explanation / bypass instructions

### ISSUE THREAD

**Issue by Spooffy** [ethangreen-dev/lovely-injector#67]
I've been trying to download a mod that requires lovely, however it has been 50 minutes since I've started and I'm no closer. There's no video that explains what I'm doing, and I've found no explanation for how to do it, plus the mod you tell me to download is causing my computer to flag it as a virus. I have no idea what I'm doing and since your a mod creator I feel like the main part of making a mod is the EXPLANATION!!!

**Comment by Aurelius7309** [comment]
The installation process is documented here: https://github.com/ethangreen-dev/lovely-injector?tab=readme-ov-file#manual-installation
For anti-virus issues, refer to this: https://github.com/Steamopollys/Steamodded/wiki/01.-Getting-started#about-anti-virus-issues
I agree this should be clarified on Lovely's page as well. For issues while downloading, that's a browser issue and can be resolved by using Firefox, though this should also be clarified in the instructions.

**Comment by ethangreen-dev** [comment]
Yeah, I think that AV info should be in our readme.

**Comment by ethangreen-dev** [comment]
Closing in favor of #61
