### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by antipatico** [ethangreen-dev/lovely-injector#72]
Hi!

First and foremost thanks for the project! I am currently working on packaging this software for a Linux distribution (NixOS). I noticed the license is missing, that makes my packaging harder. Is this project free? If so, what license does it have? It may be worthy to add a license at the root of this project.

Thanks again!

**Comment by ethangreen-dev** [comment]
Taking care of this ASAP, thanks!

**Comment by ethangreen-dev** [comment]
#75
