### ISSUE TITLE
Option to disable the log console

### ISSUE THREAD

**Issue by TropheusJ** [ethangreen-dev/lovely-injector#77]
Would be nice to be able to disable it when you don't need it. Maybe disable it by default since the average user will probably never need it

**Comment by BNTFryingPan** [comment]
use `--disable-console`

**Comment by ssyangchn** [comment]
> use `--disable-console`

Could you please provide more details on how to add --disable-console?

**Comment by BNTFryingPan** [comment]
that depends on where you are running the game you are modding. on steam it goes in the launch options

**Comment by ssyangchn** [comment]
> that depends on where you are running the game you are modding. on steam it goes in the launch options

![Image](https://github.com/user-attachments/assets/b95e9b97-3fd6-4054-bcb1-60d62b86d9f0)

i do. but it not work
