### ISSUE TITLE
Problem LibLovely 5.0 beta 7

### ISSUE THREAD

**Issue by guillaumetallandier** [ethangreen-dev/lovely-injector#85]
The lib is looking for the "BalatroN.app" folder and not "Balatro.app" . So it always fail on MAC OS. 
The previous lib work fine.

**Comment by ethangreen-dev** [comment]
Hey, closing this under the assumption that you have resolved this problem. If this isn't the case @ me with further details about your environment and what you've done to debug your problem as it may be a bug within lovely. Thanks
