### ISSUE TITLE
Balatro Crash

### ISSUE THREAD

**Issue by dathide** [ethangreen-dev/lovely-injector#90]
Refreshing the shop on this save crashes the game.
[lovely-2024.11.06-19.10.29.log](https://github.com/user-attachments/files/17655733/lovely-2024.11.06-19.10.29.log)
[save.jkr.zip](https://github.com/user-attachments/files/17655738/save.jkr.zip)

**Comment by autisticgamer-500** [comment]
I tried modding balatro again for the first time in a while and the game doesnt even boot up. I get this error
`Oops! The game crashed:
Syntax error: functions/state_events.lua:970: unexpected symbol near '}'


Additional Context:
Balatro Version: 1.0.1m-FULL
Modded Version: ???
Love2D Version: 11.5.0
Lovely Version: 0.6.0

Stack Traceback
===============
(3)  C function 'function: 0x1a62cee8'
(4) global C function 'require'
(5) main chunk of file 'main.lua' at line 854
(6) global C function 'require'
(7) Love2D function at file 'boot.lua:323' (best guess)
Local variables:
 c = table: 0x1a629c68  {identity:false, version:11.5, accelerometerjoystick:true, modules:table: 0x1a629cb8 (more...)}
 openedconsole = boolean: false
 confok = boolean: true
 conferr = nil
(8) global C function 'xpcall'
(9) Love2D function at file 'boot.lua:362' (best guess)
Local variables:
 result = boolean: true
(10) global C function 'xpcall'
(11) Love2D function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])
 inerror = boolean: true
 deferErrhand = Lua function '(Love2D Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])
`

**Comment by ethangreen-dev** [comment]
Hey, closing this as I'm assuming that both of you have resolved your issues with help from somewhere else. A gentle reminder that game-specific crashes should be initially queried in a help channel. An issue becomes appropriate when it is the result of a bug within lovely.
