### ISSUE TITLE
lovely crashed on first start

### ISSUE THREAD

**Issue by craftman1971** [ethangreen-dev/lovely-injector#94]
INFO - [G] Error: Syntax error: game.lua:4: '=' expected near 'Game'

stack traceback:
	[love "boot.lua"]:352: in function <[love "boot.lua"]:348>
	[C]: at 0x7ff937cd2fa0
	[C]: in function 'require'
	main.lua:16: in main chunk
	[C]: in function 'require'
	[love "boot.lua"]:323: in function <[love "boot.lua"]:126>
	[C]: in function 'xpcall'
	[love "boot.lua"]:362: in function <[love "boot.lua"]:355>
	[C]: in function 'xpcall'

**Comment by Aurelius7309** [comment]
Verify game files on steam
