### ISSUE TITLE
Can't Launch my SteamLauncher due to lovely-injector

### ISSUE THREAD

**Issue by D3athstep** [ethangreen-dev/lovely-injector#97]
I am unable to launch steam launcher that I use to play steam games on offline mode. Whenever I try to run the launcher it gives exception that 
"ERROR - [♥] lovely-injector has crashed: 
panicked at crates\lovely-win\src\lib.rs:68:48:
called `Result::unwrap()` on an `Err` value: Error { code: HRESULT(0x8007007E), message: "The specified module could not be found." }
ERROR - [♥] lovely-injector has crashed: 
panicked at core\src\panicking.rs:221:5:
panic in a function that cannot unwind"

Is there a way to completely uninstall the injector

**Comment by ethangreen-dev** [comment]
@D3athstep You can uninstall lovely by deleting `version.dll` inside of the game directory. I cannot reproduce your issue nor offer you any real kind of support due to your offline Steam launcher.

**Comment by maheussemt** [comment]
i have the same issue

**Comment by HaewonLover** [comment]
> i have the same issue

if you're using the Xbox game pass version of Balatro then Lovely will say this, not sure if that's what you did but i tried and it didn't work sadly

**Comment by SmartThinker14** [comment]
I had this same issue for my pc i dont know an actually fix but you have to delete all of the version.dll in your pc not including recycle bin, i know im a bit late to this but for anyone one in the future you gotta look through your pc and delete any lovely injectors/ version.dll that are from lovely
