### ISSUE TITLE
I'm not sure if i should put this in steam modded or here, gonna be honest have no clue what to do.

### ISSUE THREAD

**Issue by ETSELG** [ethangreen-dev/lovely-injector#98]
![image](https://github.com/user-attachments/assets/95eab2f1-8c06-4c32-8cda-126adb998b1e)

**Comment by ethangreen-dev** [comment]
@ETSELG You have an old version of lovely. Update it and things should start working again. If not then you should ask for help in the #modding-chat channel of the Balatro Discord.
