### ISSUE TITLE
Game just boots up to an Error screen

### ISSUE THREAD

**Issue by IrnoO** [ethangreen-dev/lovely-injector#99]
i have no idea what is wrong or what any of this means
![image_2024-12-22_123902850](https://github.com/user-attachments/assets/7aaf9e0b-1942-4287-b2f9-47c007da263c)
so if anyone knows and can explain that would be nice

**Comment by ethangreen-dev** [comment]
Hey @IrnoO, validate your game files via Steam and it should resolve your issue.
